services:
  queue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: queue-app
    ports:
      - "4200:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
